/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const PayIdLazyImport = createFileRoute('/pay/$id')()
const DetailIdLazyImport = createFileRoute('/detail/$id')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PayIdLazyRoute = PayIdLazyImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pay/$id.lazy').then((d) => d.Route))

const DetailIdLazyRoute = DetailIdLazyImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/detail/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/detail/$id': typeof DetailIdLazyRoute
  '/pay/$id': typeof PayIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/detail/$id': typeof DetailIdLazyRoute
  '/pay/$id': typeof PayIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/detail/$id': typeof DetailIdLazyRoute
  '/pay/$id': typeof PayIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detail/$id' | '/pay/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detail/$id' | '/pay/$id'
  id: '__root__' | '/' | '/detail/$id' | '/pay/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DetailIdLazyRoute: typeof DetailIdLazyRoute
  PayIdLazyRoute: typeof PayIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DetailIdLazyRoute: DetailIdLazyRoute,
  PayIdLazyRoute: PayIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/detail/$id",
        "/pay/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/detail/$id": {
      "filePath": "detail/$id.lazy.tsx"
    },
    "/pay/$id": {
      "filePath": "pay/$id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
